version: '3.6'

services:
    sim-global-follower:
        image: registry.opendlv.org/testing/opendlv-virtual-space:v0.0.8
        network_mode: "host"
        # command: "/usr/bin/opendlv-virtual-space --cid=111 --freq=50 --frame-id=0 --x=0.768 --y=1.46 --yaw=2.87 --timemod=0.05"
        command: "/usr/bin/opendlv-virtual-space --cid=111 --freq=50 --frame-id=0 --x=0.8 --y=1.6 --yaw=-3.14 --timemod=0.01 --extra-cid-out=112:1"

    sim-motor-kiwi-follower:
        image: chalmersrevere/opendlv-sim-motor-kiwi-amd64:v0.0.7
        network_mode: "host"
        command: "/usr/bin/opendlv-sim-motor-kiwi --cid=111 --freq=50 --frame-id=0 --timemod=0.01"

    sim-ultrasonic-srf08-front-follower:
        image: registry.opendlv.org/testing/opendlv-virtual-rangefinder-ultrasonic-srf08:v0.0.6
        network_mode: "host"
        volumes:
          - ./conetrack/:/opt/map/
        command: "/usr/bin/opendlv-virtual-rangefinder-ultrasonic-srf08 --map-file=/opt/map/ --x=0.2 --y=0.0 --yaw=0.0 --cid=111 --freq=10 --frame-id=0 --id=0"
    
    sim-ultrasonic-srf08-rear-follower:
        image: registry.opendlv.org/testing/opendlv-virtual-rangefinder-ultrasonic-srf08:v0.0.6
        network_mode: "host"
        volumes:
          - ./conetrack/:/opt/map/
        command: "/usr/bin/opendlv-virtual-rangefinder-ultrasonic-srf08 --map-file=/opt/map/ --x=-0.2 --y=0.0 --yaw=3.14 --cid=111 --freq=10 --frame-id=0 --id=1"
    
    sim-adc-bbblue-left-follower:
        image: registry.opendlv.org/testing/opendlv-virtual-adc-bbblue:v0.0.7
        network_mode: "host"
        volumes:
          - ./conetrack/:/opt/map/
        command: "/usr/bin/opendlv-virtual-adc-bbblue --map-file=/opt/map/ --x=0.0 --y=0.1 --yaw=1.57 --cid=111 --freq=10 --frame-id=0 --id=2"
    
    sim-adc-bbblue-right-follower:
        image: registry.opendlv.org/testing/opendlv-virtual-adc-bbblue:v0.0.7
        network_mode: "host"
        volumes:
          - ./conetrack/:/opt/map/
        command: "/usr/bin/opendlv-virtual-adc-bbblue --map-file=/opt/map/ --x=0.0 --y=-0.1 --yaw=-1.57 --cid=111 --freq=10 --frame-id=0 --id=3"
    
    logic-test-kiwi-follower:
        image: registry.git.chalmers.se/courses/tme290/2022/group12/autonomousrobot/actuation:v2amd64
        # image: registry.git.chalmers.se/courses/tme290/2022/group12/autonomousrobot/actuation:v2armhf # for armhf platform
        network_mode: "host"
        restart: on-failure
        command: "/usr/bin/opendlv-logic-test-kiwi --cid=111 --freq=10"

    sim-camera-follower:
        container_name: sim-camera-follower
        image: chalmersrevere/opendlv-sim-camera-mesa:v0.0.1
        ipc: "host"
        network_mode: "host"
        volumes:
          - ${PWD}/conetrack:/opt/map/
          - /tmp:/tmp
        environment:
          - DISPLAY=${DISPLAY}
        command: "--cid=111 --frame-id=0 --map-path=/opt/map/ --x=0.0 --z=0.095 --width=1280 --height=720 --fovy=48.8 --freq=10 --timemod=0.01 --name.argb=video0.argb --verbose"

    opendlv-kiwi-view-follower:
        image: chrberger/opendlv-kiwi-view-webrtc-multi:v0.0.6
        network_mode: "host"
        volumes:
          - ~/recordings:/opt/vehicle-view/recordings
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - PORT=8081
          - OD4SESSION_CID=111
          - PLAYBACK_OD4SESSION_CID=253

    opendlv-perception-follower:
        image: registry.git.chalmers.se/courses/tme290/2022/group12/autonomousrobot/perception:latest
        network_mode: "host"
        ipc: "host"
        restart: on-failure
        volumes:
          - /tmp:/tmp
        environment:
          - DISPLAY=${DISPLAY}
        command: "--cid=111 --name=video0.argb --width=1280 --height=720"

    sim-camera-lead:
        container_name: sim-camera-lead
        image: chalmersrevere/opendlv-sim-camera-mesa:v0.0.1
        ipc: "host"
        network_mode: "host"
        volumes:
          - ${PWD}/conetrack:/opt/map/
          - /tmp:/tmp
        environment:
          - DISPLAY=${DISPLAY}
        command: "--cid=112 --frame-id=1 --map-path=/opt/map/ --x=0.0 --z=0.095 --width=1280 --height=720 --fovy=48.8 --freq=10 --timemod=0.01 --name.argb=video1.argb --verbose"

    sim-global-lead:
      image: chalmersrevere/opendlv-sim-global-amd64:v0.0.7
      network_mode: "host"
      command: "/usr/bin/opendlv-sim-global --cid=112 --freq=50 --timemod=0.01 --frame-id=1 --x=0.3 --y=1.6 --yaw=-3.14 --extra-cid-out=111:1"

    sim-motor-kiwi-lead:
      image: chalmersrevere/opendlv-sim-motor-kiwi-amd64:v0.0.7
      network_mode: "host"
      command: "/usr/bin/opendlv-sim-motor-kiwi --cid=112 --freq=200 --timemod=0.01 --frame-id=1"

    opendlv-kiwi-view-lead:
      image: chrberger/opendlv-kiwi-view-webrtc-multi:v0.0.6
      network_mode: "host"
      volumes:
        - ~/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - PORT=8082
        - OD4SESSION_CID=112
        - PLAYBACK_OD4SESSION_CID=254

    logic-test-kiwi-lead:
          image: registry.git.chalmers.se/courses/tme290/2022/group12/autonomousrobot/actuation:v2amd64
        # image: registry.git.chalmers.se/courses/tme290/2022/group12/autonomousrobot/actuation:v2armhf # for armhf platform
          network_mode: "host"
          restart: on-failure
          command: "/usr/bin/opendlv-logic-test-kiwi --cid=112 --freq=10"

    sim-ultrasonic-srf08-front-lead:
        image: registry.opendlv.org/testing/opendlv-virtual-rangefinder-ultrasonic-srf08:v0.0.6
        network_mode: "host"
        volumes:
          - ./conetrack/:/opt/map/
        command: "/usr/bin/opendlv-virtual-rangefinder-ultrasonic-srf08 --map-file=/opt/map/ --x=0.2 --y=0.0 --yaw=0.0 --cid=112 --freq=10 --frame-id=1 --id=0"
    
    sim-ultrasonic-srf08-rear-lead:
        image: registry.opendlv.org/testing/opendlv-virtual-rangefinder-ultrasonic-srf08:v0.0.6
        network_mode: "host"
        volumes:
          - ./conetrack/:/opt/map/
        command: "/usr/bin/opendlv-virtual-rangefinder-ultrasonic-srf08 --map-file=/opt/map/ --x=-0.2 --y=0.0 --yaw=3.14 --cid=112 --freq=10 --frame-id=1 --id=1"
    
    sim-adc-bbblue-left-lead:
        image: registry.opendlv.org/testing/opendlv-virtual-adc-bbblue:v0.0.7
        network_mode: "host"
        volumes:
          - ./conetrack/:/opt/map/
        command: "/usr/bin/opendlv-virtual-adc-bbblue --map-file=/opt/map/ --x=0.0 --y=0.1 --yaw=1.57 --cid=112 --freq=10 --frame-id=1 --id=2"
    
    sim-adc-bbblue-right-lead:
        image: registry.opendlv.org/testing/opendlv-virtual-adc-bbblue:v0.0.7
        network_mode: "host"
        volumes:
          - ./conetrack/:/opt/map/
        command: "/usr/bin/opendlv-virtual-adc-bbblue --map-file=/opt/map/ --x=0.0 --y=-0.1 --yaw=-1.57 --cid=112 --freq=10 --frame-id=1 --id=3"

    opendlv-perception-lead:
        image: registry.git.chalmers.se/courses/tme290/2022/group12/autonomousrobot/perception:latest
        network_mode: "host"
        ipc: "host"
        restart: on-failure
        volumes:
          - /tmp:/tmp
        environment:
          - DISPLAY=${DISPLAY}
        command: "--cid=112 --name=video1.argb --width=1280 --height=720"